"""BackStudio CLI entry point."""

import os
import secrets
import subprocess
import sys
import webbrowser
from pathlib import Path

import typer

from app.erd.loader import ERDValidationError, load_erd
from app.erd.translate import translate
from app.erd.visualize import render_html
from app.services.code_generator import CodeGenerator

app = typer.Typer(name="backstudio", help="Generate FastAPI backends from a YAML ERD.")

_MAX_SUBPROCESS_OUTPUT = 4000


def _decode_and_truncate(output: object) -> str:
    """Decode subprocess stdout/stderr (bytes or str) and cap it to a sane length."""
    if not output:
        return ""
    text = output.decode("utf-8", errors="replace") if isinstance(output, bytes) else str(output)
    text = text.strip()
    if not text:
        return ""
    if len(text) > _MAX_SUBPROCESS_OUTPUT:
        text = text[:_MAX_SUBPROCESS_OUTPUT] + "\n... (truncated)"
    return text + "\n"


def _ensure_dev_env_secret(project_dir: Path, secret_env_var: str) -> str | None:
    """Write a freshly-generated random secret to <project_dir>/.env for local dev.

    Does nothing (returns None) if the env var is already set in the current process,
    or if a .env file already exists (never overwrites one, e.g. on a --force
    regeneration where the user may have already customized it). Returns the path
    written to on success, for the caller to report to the user.
    """
    if os.getenv(secret_env_var):
        return None

    env_path = project_dir / ".env"
    if env_path.exists():
        return None

    secret_value = secrets.token_hex(32)
    env_path.write_text(
        f"# Auto-generated by `backstudio generate` for local development.\n"
        f"# Replace with a securely-managed secret before deploying anywhere real.\n"
        f"{secret_env_var}={secret_value}\n",
        encoding="utf-8",
    )
    # Make it available in this process too, so the Alembic subprocess below (which
    # inherits the current environment) can actually use it without a second run.
    os.environ[secret_env_var] = secret_value
    return str(env_path)


@app.callback(invoke_without_command=True)
def main(ctx: typer.Context) -> None:
    """BackStudio CLI."""
    pass


@app.command()
def validate(
    erd_file: Path = typer.Argument(..., exists=True, readable=True, help="Path to the ERD YAML file")
) -> None:
    """Validate an ERD file without generating anything."""
    try:
        erd = load_erd(erd_file)
    except ERDValidationError as exc:
        typer.secho(str(exc), fg=typer.colors.RED)
        raise typer.Exit(code=1)

    relationship_count = sum(len(e.relationships) for e in erd.entities)
    typer.secho(
        f"OK: {len(erd.entities)} entities, {relationship_count} relationships, "
        f"auth={'on' if erd.auth.enabled else 'off'}, rbac={'on' if erd.rbac.enabled else 'off'}",
        fg=typer.colors.GREEN,
    )


@app.command()
def visualize(
    erd_file: Path = typer.Argument(..., exists=True, readable=True, help="Path to the ERD YAML file"),
    output: Path = typer.Option(None, "--output", "-o", help="Output HTML path"),
    open_browser: bool = typer.Option(True, "--open/--no-open", help="Open the diagram in a browser"),
) -> None:
    """Render an HTML ER diagram for the given ERD file."""
    try:
        erd = load_erd(erd_file)
    except ERDValidationError as exc:
        typer.secho(str(exc), fg=typer.colors.RED)
        raise typer.Exit(code=1)

    html = render_html(erd)
    out_path = output or erd_file.with_name(f"{erd_file.stem}-diagram.html")
    out_path.write_text(html, encoding="utf-8")
    typer.secho(f"Diagram written to: {out_path}", fg=typer.colors.GREEN)

    if open_browser:
        webbrowser.open(out_path.resolve().as_uri())


@app.command()
def generate(
    erd_file: Path = typer.Argument(..., exists=True, readable=True, help="Path to the ERD YAML file"),
    output: Path = typer.Option(
        Path("."), "--output-dir", "-o", help="Directory the generated project lands in (default: current directory)"
    ),
    force: bool = typer.Option(False, "--force", help="Overwrite existing generated code"),
) -> None:
    """Generate a FastAPI backend from an ERD file."""
    try:
        erd = load_erd(erd_file)
    except ERDValidationError as exc:
        typer.secho(str(exc), fg=typer.colors.RED)
        raise typer.Exit(code=1)

    state = translate(erd)
    generator = CodeGenerator(output_dir=str(output))

    # generate_project(force=True) deletes and recreates the whole project directory —
    # including any .env a previous run wrote — so preserve one across a --force
    # regeneration rather than silently rotating the user's secret on every re-run.
    predicted_env_path = output / state["name"] / ".env"
    preserved_env_content = (
        predicted_env_path.read_text(encoding="utf-8") if predicted_env_path.exists() else None
    )

    try:
        project_dir = generator.generate_project(state, force=force)
    except FileExistsError as exc:
        typer.secho(str(exc), fg=typer.colors.RED)
        typer.secho("Use --force to overwrite.", fg=typer.colors.YELLOW)
        raise typer.Exit(code=1)

    if preserved_env_content is not None:
        (project_dir / ".env").write_text(preserved_env_content, encoding="utf-8")
    elif erd.auth.enabled:
        secret_env_var = erd.auth.jwt.secret_env_var
        written_env_path = _ensure_dev_env_secret(project_dir, secret_env_var)
        if written_env_path:
            typer.secho(
                f"Generated a random {secret_env_var} for local development and wrote it to "
                f"{written_env_path}. Replace it with a securely-managed secret before deploying.",
                fg=typer.colors.CYAN,
            )

    if (project_dir / "alembic.ini").exists():
        try:
            subprocess.run(
                [sys.executable, "-m", "alembic", "revision", "--autogenerate", "-m", "initial"],
                cwd=project_dir,
                check=True,
                capture_output=True,
                timeout=30,
            )
        except subprocess.CalledProcessError as exc:
            detail = _decode_and_truncate(exc.stdout) + _decode_and_truncate(exc.stderr)
            typer.secho(
                f"Warning: could not auto-generate the initial Alembic migration "
                f"(exit code {exc.returncode}). You can run it yourself once the "
                f"database is reachable.\n{detail}",
                fg=typer.colors.YELLOW,
            )
        except Exception as exc:  # best-effort: never fails `generate`
            typer.secho(
                f"Warning: could not auto-generate the initial Alembic migration ({exc}). "
                "You can run it yourself once the database is reachable.",
                fg=typer.colors.YELLOW,
            )

    typer.secho(f"Generated at: {project_dir}", fg=typer.colors.GREEN, bold=True)
    typer.echo("Copy this directory into your project.")


if __name__ == "__main__":
    app()
